# This module takes the sub-queries generated by the planner, connects to the Tavily API, and executes concurrent web searches to fetch relevant articles, snippets, and source URLs.

import asyncio
from typing import List, Dict, Any
from tavily import TavilyClient
from config.settings import settings

class SearchExecutor:
    """
    Step 2: Executes parallel web and database searches using the Tavily API.
    """
    def __init__(self):
        if not settings.TAVILY_API_KEY:
            raise ValueError("TAVILY_API_KEY is missing from environment variables or settings.")
        self.client = TavilyClient(api_key=settings.TAVILY_API_KEY)
        self.max_results = settings.MAX_SEARCH_RESULTS_PER_QUERY

    def execute_single_query(self, query: str) -> Dict[str, Any]:
        """
        Executes a single search query via Tavily synchronous client.
        """
        try:
            response = self.client.search(
                query=query,
                max_results=self.max_results,
                search_depth="advanced",
                include_raw_content=True
            )
            return {
                "query": query,
                "results": response.get("results", []),
                "error": None
            }
        except Exception as e:
            return {
                "query": query,
                "results": [],
                "error": str(e)
            }

    async def execute_searches_async(self, queries: List[str]) -> List[Dict[str, Any]]:
        """
        Executes multiple search queries concurrently using asyncio.
        """
        loop = asyncio.get_running_loop()
        tasks = [
            loop.run_in_executor(None, self.execute_single_query, q)
            for q in queries
        ]
        results = await asyncio.gather(*tasks)
        return results

    def execute_searches(self, queries: List[str]) -> List[Dict[str, Any]]:
        """
        Synchronous wrapper to run concurrent searches.
        """
        return asyncio.run(self.execute_searches_async(queries))